# Generated by Django 4.2 on 2023-11-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_upload', models.DateField(max_length=200)),
                ('uploader_name', models.CharField(max_length=400)),
            ],
        ),
    ]
