# Generated by Django 4.2 on 2023-11-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0003_alter_purchase_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product_details.products'),
        ),
    ]
