# Generated by Django 4.2 on 2023-11-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0004_purchase_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_details.products'),
        ),
    ]
