# Generated by Django 4.2 on 2023-04-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Mail_id',
            field=models.EmailField(default='no_mail@null', max_length=300),
        ),
        migrations.AddField(
            model_name='signup',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='Password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
